### ISSUE TITLE
Beamer: Page rnumbering still wrong

### ISSUE THREAD

**Issue by boldt** [kellertuer/UzL-Design#2]
Moin Ronny,

Irgendwas stimmt da leider mit den Seitenzahlen hinten und vorne nicht:

https://github.com/kellertuer/UzL-Design/blob/master/LaTeX-Beamer/example-pres.pdf

* 1/3
* 1/2
* 2/3
* [plain]
* 1/1

In dem TUKL-Design scheint das zu passen:

https://github.com/kellertuer/TUKL-Design/blob/master/LaTeX-Beamer/example-pres-xelatex.pdf

Gruß Dennis

**Comment by kellertuer** [comment]
Hallo Dennis,
hehe. Doch diese vorne-und-hinten-nicht-stimmenden Seitenzahlen kann man auch im TUKL-Design aktivieren. Du musst nur mal im Code schauen; die option „reducedframetotal“ folgt einer ganz einfachen Regel: Brüche kann man kürzen. Bei den 6 Folien wird auf der ersten Seite keine Zahl angezeigt, die zweite wäre 2/6, aber das kann man ja zu 1/3 kürzen. Analog bei der nächsten, denn 3/6 = 1/2.

Ob das nun sinnvoll ist - ist natürlich eine andere Frage. Aber anschalten kann man das auch im TUKL.

Kurz: It's not a bug it's a feature. “displayframetotal” gibt dir die normale Anzeige mit ungekürzen Anzahlen.

Viele Grüße
Ronny

PS: Warum eigentlich „still wrong“?

**Comment by boldt** [comment]
reducedframetotal entfenrt. Jetzt ist es wie ich es erwarte
